### ISSUE TITLE
Is this still under development?

### ISSUE THREAD

**Issue by gcormier** [ArduinoHannover/ZPB30A1_Firmware#5]
Just curious if it's still being worked on. Very cool!

The MCU is rather difficult to find - Mouser has some on order, Digikey doesn't regular stock, and AliExpress it's in units of 10. Is there any other pin-compatible version of STM8S005K6 that's nearly identical but is slightly more available?

Here's some potential equivalents from the STM product selector?

![image](https://user-images.githubusercontent.com/8388983/45255084-1ff97d80-b350-11e8-8939-dcc0649f1415.png)

STM8S207K6T6C has identical pinouts.

**Comment by Benik3** [comment]
I just got mine today from eBay :)
https://www.ebay.com/itm/Original-STM8S005K6T6C-Microcontroller-8-bit-VALUE-LINE-LQFP-32/253122272505

**Comment by Benik3** [comment]
BTW I would like also to know, if author is still working on it.
I just tried to compile the code from dev branch, and it contains LOT of errors.
I tried to fix it but now I'm not able to fix error with putchar declaration :/

**Comment by Benik3** [comment]
Heureka! I had to comment out definition of putchar in stdio.h.
Here is compiled FW.
I successfully flashed it into the STM, it's working pretty fine, there are maybe only some little bug in display and I didn't get any beeps even with beeper ON :/

[electronic_load.zip](https://github.com/ArduinoHannover/ZPB30A1_Firmware/files/2443424/electronic_load.zip)

**Comment by zerog2k** [comment]
@Benik3 did you flash mcu on the board? If so, how did you do it? Did you erase? Did you set option bits (OPT2[AFR7] ) for buzzer pin functionality?

AFR7 Alternate function remapping option 7
0: AFR7 remapping option inactive: default alternate function
1: Port D4 alternate function = BEEP

**Comment by Benik3** [comment]
Yes, I replaced the chip and flashed it on the board. You can solder a pin header  on front of the load for programming. New chip was clean, but I erased it also many times.  
You should be also able to unlock the original chip through SWIM. I didn't try it, because I want to save the original SW. But if you flash 0x00 Option bytes, you should clear the ROP. Of course you will lost original SW...  
That I have to set Option bytes for Buzzer I found yesterday :D I want to add it directly into FW, but it won't work for me. So now I set it through graphic STVP.  
If you are interested, I forked this repository:
https://github.com/Benik3/ZPB30A1_Firmware/tree/dev
